### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by moriarty** [PickNikRobotics/picknik_controllers#8]
I think I missed something when I renamed.
@MarqRazz & @abake48 should I rename this before creating a binary release?

Should this be `picknik_reset_fault_controller/ResetFaultController`?

Edit: I think it should be `picknik_reset_fault_controller/PicknikResetFaultController` and submitted a PR. 

https://github.com/PickNikRobotics/ros2_kortex/pull/145

https://github.com/PickNikRobotics/picknik_controllers/blob/6f90ec37e55bf8756a458448e97f2bbac101cebd/picknik_reset_fault_controller/controller_plugins.xml#L2

**Comment by MarqRazz** [comment]
I agree it should be `picknik_reset_fault_controller/PicknikResetFaultController` because it will make it easier to change the service message which should hopefully be happening soon.
